export const postsMock = [
  {
    id: 1,
    content: 'Content 1',
    createdAt: new Date().toISOString(),
    likes: 5,
    activeUserLikedIt: 1,
    loves: 0,
    activeUserLovedIt: 0,
    author: {
      id: 1,
      username: 'John Doe',
    },
  },
  {
    id: 2,
    content: 'Content 2',
    createdAt: new Date().toISOString(),
    likes: 5,
    activeUserLikedIt: 1,
    loves: 0,
    activeUserLovedIt: 0,
    author: {
      id: 1,
      username: 'John Doe',
    },
  },
  {
    id: 3,
    content: 'Content 3',
    createdAt: new Date().toISOString(),
    likes: 5,
    activeUserLikedIt: 1,
    loves: 0,
    activeUserLovedIt: 0,
    author: {
      id: 1,
      username: 'John Doe',
    },
  },
  {
    id: 4,
    content: 'Content 4',
    createdAt: new Date().toISOString(),
    likes: 5,
    activeUserLikedIt: 1,
    loves: 0,
    activeUserLovedIt: 0,
    author: {
      id: 1,
      username: 'John Doe',
    },
  },
  {
    id: 5,
    content: 'Content 5',
    createdAt: new Date().toISOString(),
    likes: 5,
    activeUserLikedIt: 1,
    loves: 0,
    activeUserLovedIt: 0,
    author: {
      id: 1,
      username: 'John Doe',
    },
  },
  {
    id: 6,
    content: 'Content 6',
    createdAt: new Date().toISOString(),
    likes: 5,
    activeUserLikedIt: 1,
    loves: 0,
    activeUserLovedIt: 0,
    author: {
      id: 1,
      username: 'John Doe',
    },
  },
  {
    id: 7,
    content: 'Content 7',
    createdAt: new Date().toISOString(),
    likes: 5,
    activeUserLikedIt: 1,
    loves: 0,
    activeUserLovedIt: 0,
    author: {
      id: 1,
      username: 'John Doe',
    },
  },
  {
    id: 8,
    content: 'Content 8',
    createdAt: new Date().toISOString(),
    likes: 5,
    activeUserLikedIt: 1,
    loves: 0,
    activeUserLovedIt: 0,
    author: {
      id: 1,
      username: 'John Doe',
    },
  },
  {
    id: 9,
    content: 'Content 9',
    createdAt: new Date().toISOString(),
    likes: 5,
    activeUserLikedIt: 1,
    loves: 0,
    activeUserLovedIt: 0,
    author: {
      id: 1,
      username: 'John Doe',
    },
  },
  {
    id: 10,
    content: 'Content 10',
    createdAt: new Date().toISOString(),
    likes: 5,
    activeUserLikedIt: 1,
    loves: 0,
    activeUserLovedIt: 0,
    author: {
      id: 1,
      username: 'John Doe',
    },
  },
];